#!/usr/bin/python
import rospy
from std_msgs.msg import Bool

class SRCDoorController:

    def __init__(self):
        rospy.init_node("src_door_controller")
        button_sub = rospy.Subscriber("/button_pressed", Bool, callback=self.buttonPressed)
        self.door_pub = rospy.Publisher("/open_door", Bool, queue_size=1)

    def buttonPressed(self, button_msg):
        if button_msg.data:
            door_msg = Bool()
            door_msg.data = True
            self.door_pub.publish(door_msg)


if __name__ == "__main__":
    src_door_controller = SRCDoorController()
    rospy.spin()
